version: '3.3'
services:

  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: minibaevaidar/foodgram_web1:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: minibaevaidar/foodgram_frontend:v1
    volumes:
      - ../frontend:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/static/
      - media_value:/media/
      - result_build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
    depends_on:
      - frontend
    env_file:
      - ./.env

volumes:
  static_value:
  media_value:
  result_build:
  postgres_data: